[project]
name = 'stx-bfaktory-sso-test'
description = 'Testing STX-bfaktory Single-Sided Opportunity Contract'
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP102V8P0F7JX67ARQ77WEA3D3CFB5XW39REDT0AM.amm-pool-v2-01'

[[project.requirements]]
contract_id = 'SP1KK89R86W73SJE6RQNQPRDM471008S9JY4FQA62.token-wbfaktory'

[[project.requirements]]
contract_id = 'SP102V8P0F7JX67ARQ77WEA3D3CFB5XW39REDT0AM.token-wstx-v2'

[contracts.stx-bfaktory-sso]
path = 'contracts/stx-bfaktory-sso.clar'
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = true
api_url = 'https://api.hiro.so'