[project]
name = 'welshies'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.linear-bonus-lock]
path = 'contracts/linear-bonus-lock.clar'
clarity_version = 3
epoch = 3.1

[contracts.lockup]
path = 'contracts/lockup.clar'
clarity_version = 3
epoch = 3.1

[contracts.welshcorgicoin-faktory-pool]
path = 'contracts/welshcorgicoin-faktory-pool.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
