[project]
name = 'welshies'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = [
   {contract_id = "SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.dexterity-traits-v0", epoch = "3.0", clarity_version = 2},
   {contract_id = "SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.charisma-traits-v1", epoch = "3.1", clarity_version = 3},
   {contract_id = "SPV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RCJDC22.welshcorgicoin-faktory-pool", epoch = "3.1", clarity_version = 3},
   {contract_id = "SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token", epoch = "3.1", clarity_version = 3},
   {contract_id = "SP3NE50GEXFG9SZGTT51P40X2CKYSZ5CC4ZTZ7A2G.welshcorgicoin-token", epoch = "3.1", clarity_version = 3}
]

[contracts.lockup]
path = 'contracts/lockup.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = true
api_url = 'https://api.hiro.so'